steps:
  # Step 1: Deploy DAG to Dev Composer bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - Dags/*.py
      - gs://us-central1-composer-dev-25fb2302-bucket/dags/

  # Optional: Wait or manual approval here (not added now)

  # Step 2: Deploy DAG to Prod Composer bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - Dags/*.py
      - gs://us-central1-composer-prod-7873bc71-bucket/dags/

options:
  logging: CLOUD_LOGGING_ONLY
